// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactNative = require("react-native");

var styles = ReactNative.StyleSheet.create({
      container: {
        alignItems: "center",
        flex: 1,
        justifyContent: "center"
      },
      welcome: {
        fontSize: 20,
        textAlign: "center",
        margin: 10
      },
      instructions: {
        textAlign: "center",
        marginBottom: 5
      }
    });

function App$app(Props) {
  var os = ReactNative.Platform.OS;
  return React.createElement(ReactNative.View, {
              style: styles.container,
              children: null
            }, React.createElement(ReactNative.Text, {
                  style: styles.welcome,
                  children: "Welcome to (Reason) React Native!"
                }), React.createElement(ReactNative.Text, {
                  style: styles.instructions,
                  children: "To get started, edit src/App.re"
                }), React.createElement(ReactNative.Text, {
                  style: styles.instructions,
                  children: os === "ios" ? "Press Cmd+R to reload,\nCmd+D or shake for dev menu" : (
                      os === "android" ? "Double tap R on your keyboard to reload,\nShake or press menu button for dev menu" : (
                          os === "web" ? "Press Cmd+R to reload." : ""
                        )
                    )
                }));
}

var View = 0;

var $$Text = 0;

var $$StyleSheet = 0;

var Style = 0;

var Platform = 0;

var app = App$app;

exports.View = View;
exports.$$Text = $$Text;
exports.$$StyleSheet = $$StyleSheet;
exports.Style = Style;
exports.Platform = Platform;
exports.styles = styles;
exports.app = app;
/* styles Not a pure module */
