// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactNative = require("react-native");

var styles = ReactNative.StyleSheet.create({
      container: {
        alignItems: "center",
        flex: 1,
        justifyContent: "center"
      },
      welcome: {
        fontSize: 20,
        textAlign: "center",
        margin: 10
      },
      instructions: {
        textAlign: "center",
        marginBottom: 5
      }
    });

function App$app(Props) {
  return React.createElement(ReactNative.View, {
              style: styles.container,
              children: null
            }, React.createElement(ReactNative.Text, {
                  style: styles.welcome,
                  children: "Welcome to (Reason) React Native!"
                }), React.createElement(ReactNative.Text, {
                  style: styles.instructions,
                  children: "To get started, edit src/App.re"
                }));
}

var View = /* alias */0;

var $$Text = /* alias */0;

var $$StyleSheet = /* alias */0;

var Style = /* alias */0;

var Platform = /* alias */0;

var app = App$app;

exports.View = View;
exports.$$Text = $$Text;
exports.$$StyleSheet = $$StyleSheet;
exports.Style = Style;
exports.Platform = Platform;
exports.styles = styles;
exports.app = app;
/* styles Not a pure module */
